### ISSUE TITLE
Remove build files from repo

### ISSUE THREAD

**Issue by enamakel** [slend3rman/Likes#1]
Build files are huge and take up substantial space in your repository. You should never commit them into Git.

Lookup what the .gitignore file does. It's a special file that git uses to know which files to ignore. 

Add your own .gitignore file and add the line `*.class` to tell git to ignore all the java class files.

**Comment by slend3rman** [comment]
Done. I have removed the .class file and added a .gitignore.

**Comment by enamakel** [comment]
Very nice! now all you have to do is close this issue.
