### ISSUE TITLE
Properly format your code and leave docstrings

### ISSUE THREAD

**Issue by enamakel** [slend3rman/Likes#3]
Eclipse has an auto-format shortcut that you can use to format your code.

And leave docstrings at least just a one liner for every function. eg:

``` java
/**
 * This function can eat n potatoes
 */
 public static void eatPotatoes(int n) {
   ...
 }
```

**Comment by enamakel** [comment]
Also by Java standards, you must leave two lines before and after function definitions. And also avoid variable names that don't make sense. 

**Avoid:**

``` java
static void printLikes (String a){
    ...
}
```

``` java
String buf; Date d;
```

**Do:**

``` java
static void printLikes (String result){
    ...
}
```

``` java
String buffer; 
Date currentDate;
```

**Comment by slend3rman** [comment]
Added docstrings and auto-formatted.
